import {
    withProps,
    ParagraphPlugin,
    PlateLeaf,
    BlockquotePlugin,
    CodeBlockPlugin,
    CodeLinePlugin,
    CodeSyntaxPlugin,
    HorizontalRulePlugin,
    LinkPlugin,
    ImagePlugin,
    MediaEmbedPlugin,
    ExcalidrawPlugin,
    TogglePlugin,
    ColumnPlugin,
    ColumnItemPlugin,
    MentionPlugin,
    MentionInputPlugin,
    TablePlugin,
    TableRowPlugin,
    TableCellPlugin,
    TableCellHeaderPlugin,
    TodoListPlugin,
    DatePlugin,
    BoldPlugin,
    ItalicPlugin,
    UnderlinePlugin,
    StrikethroughPlugin,
    CodePlugin,
    SubscriptPlugin,
    SuperscriptPlugin,
    HighlightPlugin,
    KbdPlugin,
    CommentsPlugin,
    HEADING_KEYS,
    BlockquoteElement,
    CodeBlockElement,
    CodeLineElement,
    CodeSyntaxLeaf,
    ExcalidrawElement,
    HrElement,
    ImageElement,
    LinkElement,
    ToggleElement,
    ColumnGroupElement,
    ColumnElement,
    HeadingElement,
    MediaEmbedElement,
    MentionElement,
    MentionInputElement,
    ParagraphElement,
    TableElement,
    TableRowElement,
    TableCellElement,
    TableCellHeaderElement,
    TodoListElement,
    DateElement,
    CodeLeaf,
    CommentLeaf,
    HighlightLeaf,
    KbdLeaf,
    withPlaceholders,
    withDraggables
  } from './plugin.imports'

export const overrideComponents = withDraggables(withPlaceholders(({
    [BlockquotePlugin.key]: BlockquoteElement,
    [CodeBlockPlugin.key]: CodeBlockElement,
    [CodeLinePlugin.key]: CodeLineElement,
    [CodeSyntaxPlugin.key]: CodeSyntaxLeaf,
    [ExcalidrawPlugin.key]: ExcalidrawElement,
    [HorizontalRulePlugin.key]: HrElement,
    [ImagePlugin.key]: ImageElement,
    [LinkPlugin.key]: LinkElement,
    [TogglePlugin.key]: ToggleElement,
    [ColumnPlugin.key]: ColumnGroupElement,
    [ColumnItemPlugin.key]: ColumnElement,
    [HEADING_KEYS.h1]: withProps(HeadingElement, { variant: 'h1' }),
    [HEADING_KEYS.h2]: withProps(HeadingElement, { variant: 'h2' }),
    [HEADING_KEYS.h3]: withProps(HeadingElement, { variant: 'h3' }),
    [HEADING_KEYS.h4]: withProps(HeadingElement, { variant: 'h4' }),
    [HEADING_KEYS.h5]: withProps(HeadingElement, { variant: 'h5' }),
    [HEADING_KEYS.h6]: withProps(HeadingElement, { variant: 'h6' }),
    [MediaEmbedPlugin.key]: MediaEmbedElement,
    [MentionPlugin.key]: MentionElement,
    [MentionInputPlugin.key]: MentionInputElement,
    [ParagraphPlugin.key]: ParagraphElement,
    [TablePlugin.key]: TableElement,
    [TableRowPlugin.key]: TableRowElement,
    [TableCellPlugin.key]: TableCellElement,
    [TableCellHeaderPlugin.key]: TableCellHeaderElement,
    [TodoListPlugin.key]: TodoListElement,
    [DatePlugin.key]: DateElement,
    [BoldPlugin.key]: withProps(PlateLeaf, { as: 'strong' }),
    [CodePlugin.key]: CodeLeaf,
    [CommentsPlugin.key]: CommentLeaf,
    [HighlightPlugin.key]: HighlightLeaf,
    [ItalicPlugin.key]: withProps(PlateLeaf, { as: 'em' }),
    [KbdPlugin.key]: KbdLeaf,
    [StrikethroughPlugin.key]: withProps(PlateLeaf, { as: 's' }),
    [SubscriptPlugin.key]: withProps(PlateLeaf, { as: 'sub' }),
    [SuperscriptPlugin.key]: withProps(PlateLeaf, { as: 'sup' }),
    [UnderlinePlugin.key]: withProps(PlateLeaf, { as: 'u' }),
  })))